import { PropertyProps } from "@/types/types";

export const mockProperties: PropertyProps[] = [
  {
    uniqueId: 1,
    property_name: "Dehradun Institute of Technology",
    property_slug: "dit-university",
    featured_image: ["/img/property-img/property-1.png"],
    property_logo: ["/img/property-img/property-1.png"],
    category: "University",
    property_type: "Private",
    est_year: "1998",
    property_description: "A leading private university in Uttarakhand.",
    rank: 1,
    address: "Mussourie-Diversion Road",
    pincode: 248009,
    city: "Dehradun",
    state: "Uttarakhand",
    country: "India",
    reviews: [
      { uniqueId: 101, property_id: 1, rating: 4, comment: "Great campus!" },
      { uniqueId: 102, property_id: 1, rating: 5, comment: "Excellent faculty." },
    ],
    courses: [
      {
        property_id: 1,
        course_id: "cse-btech",
        course_name: "B.Tech in Computer Science",
        course_short_name: "B.Tech CSE",
        duration: "4 Years",
        course_type: "Engineering",
        course_level: "Undergraduate",
        certification_type: "Degree",
        course_format: "Full-time",
      },
      {
        property_id: 1,
        course_id: "mba-gen",
        course_name: "Master of Business Administration",
        course_short_name: "MBA",
        duration: "2 Years",
        course_type: "Management",
        course_level: "Postgraduate",
        certification_type: "Degree",
        course_format: "Full-time",
      },
    ],
    amenities: {
      Campus: [{ "Wi-Fi": true }, { "Cafeteria": true }, { "Hostel": true }],
      Sports: [{ "Gym": true }, { "Football Ground": false }],
    },
  },
  {
    uniqueId: 2,
    property_name: "Graphic Era University",
    property_slug: "graphic-era-university",
    featured_image: ["/img/property-img/property-1.png"],
    property_logo: ["/img/property-img/property-1.png"],
    category: "University",
    property_type: "Deemed to be University",
    est_year: "1993",
    property_description: "Known for its engineering and management programs.",
    rank: 2,
    address: "Clement Town",
    pincode: 248002,
    city: "Dehradun",
    state: "Uttarakhand",
    country: "India",
    reviews: [
      { uniqueId: 201, property_id: 2, rating: 5, comment: "Top placements." },
      { uniqueId: 202, property_id: 2, rating: 4, comment: "Good infrastructure." },
    ],
    courses: [
        {
            property_id: 2,
            course_id: "cse-btech",
            course_name: "B.Tech in Computer Science",
            course_short_name: "B.Tech CSE",
            duration: "4 Years",
            course_type: "Engineering",
            course_level: "Undergraduate",
            certification_type: "Degree",
            course_format: "Online",
          },
          {
            property_id: 2,
            course_id: "bca",
            course_name: "Bachelor of Computer Applications",
            course_short_name: "BCA",
            duration: "3 Years",
            course_type: "Computer Science",
            course_level: "Undergraduate",
            certification_type: "Degree",
            course_format: "Full-time",
          },
    ],
    amenities: {
        Campus: [{ "Wi-Fi": true }, { "Cafeteria": true }, { "Hostel": true }],
        Sports: [{ "Gym": true }, { "Football Ground": true }, { "Swimming Pool": true}],
    },
  },
  {
    uniqueId: 3,
    property_name: "UPES Dehradun",
    property_slug: "upes-dehradun",
    featured_image: ["/img/property-img/property-1.png"],
    property_logo: ["/img/property-img/property-1.png"],
    category: "University",
    property_type: "Private",
    est_year: "2003",
    property_description: "University of Petroleum and Energy Studies.",
    rank: 3,
    address: "Bidholi",
    pincode: 248007,
    city: "Dehradun",
    state: "Uttarakhand",
    country: "India",
    reviews: [
      { uniqueId: 301, property_id: 3, rating: 3, comment: "A bit expensive." },
      { uniqueId: 302, property_id: 3, rating: 4, comment: "Specialized courses." },
    ],
    courses: [
        {
            property_id: 3,
            course_id: "cse-btech",
            course_name: "B.Tech in Computer Science",
            course_short_name: "B.Tech CSE",
            duration: "4 Years",
            course_type: "Engineering",
            course_level: "Undergraduate",
            certification_type: "Degree",
            course_format: "Full-time",
          },
          {
            property_id: 3,
            course_id: "llb",
            course_name: "Bachelor of Laws",
            course_short_name: "LLB",
            duration: "3 Years",
            course_type: "Law",
            course_level: "Undergraduate",
            certification_type: "Degree",
            course_format: "Full-time",
          },
    ],
    amenities: {
        Campus: [{ "Wi-Fi": true }, { "Cafeteria": false }, { "Hostel": true }],
        Sports: [{ "Gym": false }, { "Football Ground": true }],
        Labs: [{ "Computer Lab": true}]
    },
  },
];